//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QAEntities : DbContext
    {
        public QAEntities()
            : base("name=QAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Table1_GetTransactions_Result> Table1_GetTransactions(Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dataTo)
        {
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("dateFrom", dateFrom) :
                new ObjectParameter("dateFrom", typeof(System.DateTime));
    
            var dataToParameter = dataTo.HasValue ?
                new ObjectParameter("dataTo", dataTo) :
                new ObjectParameter("dataTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Table1_GetTransactions_Result>("Table1_GetTransactions", dateFromParameter, dataToParameter);
        }
    
        public virtual ObjectResult<string> Table1_ListCategory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Table1_ListCategory");
        }
    }
}
